language: objective-c
before_install:
  brew install python3
matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      env: TARGET=framework COMMAND=test FBSIMULATORCONTROL_DEVICE_SET=default FBSIMULATORCONTROL_LAUNCH_TYPE=simulator_app
    - os: osx
      osx_image: xcode7.3
      env: TARGET=framework COMMAND=test FBSIMULATORCONTROL_DEVICE_SET=custom FBSIMULATORCONTROL_LAUNCH_TYPE=simulator_app
    - os: osx
      osx_image: xcode7.3
      env: TARGET=framework COMMAND=test FBSIMULATORCONTROL_DEVICE_SET=custom FBSIMULATORCONTROL_LAUNCH_TYPE=direct
    - os: osx
      osx_image: xcode7.3
      env: TARGET=fbxctest COMMAND=build
    - os: osx
      osx_image: xcode7.3
      env: TARGET=fbxctest COMMAND=test
    - os: osx
      osx_image: xcode8
      env: TARGET=framework COMMAND=test FBSIMULATORCONTROL_DEVICE_SET=default FBSIMULATORCONTROL_LAUNCH_TYPE=simulator_app
    - os: osx
      osx_image: xcode8
      env: TARGET=framework COMMAND=test FBSIMULATORCONTROL_DEVICE_SET=custom FBSIMULATORCONTROL_LAUNCH_TYPE=simulator_app
    - os: osx
      osx_image: xcode8
      env: TARGET=framework COMMAND=test FBSIMULATORCONTROL_DEVICE_SET=custom FBSIMULATORCONTROL_LAUNCH_TYPE=direct
    - os: osx
      osx_image: xcode8
      env: TARGET=fbsimctl COMMAND=build
    - os: osx
      osx_image: xcode8
      env: TARGET=fbsimctl COMMAND=test
    - os: osx
      osx_image: xcode8
      env: TARGET=fbsimctl COMMAND=e2e-test
    - os: osx
      osx_image: xcode8
      env: TARGET=fbxctest COMMAND=build
    - os: osx
      osx_image: xcode8
      env: TARGET=fbxctest COMMAND=test
script: ./build.sh
branches:
  only:
    - master
