language: objective-c
osx_image: xcode7.3
before_install:
  brew install carthage
env:
- TARGET=framework COMMAND=test FBSIMULATORCONTROL_DEVICE_SET=default FBSIMULATORCONTROL_LAUNCH_TYPE=simulator_app
- TARGET=framework COMMAND=test FBSIMULATORCONTROL_DEVICE_SET=custom FBSIMULATORCONTROL_LAUNCH_TYPE=simulator_app
- TARGET=framework COMMAND=test FBSIMULATORCONTROL_DEVICE_SET=custom FBSIMULATORCONTROL_LAUNCH_TYPE=direct
- TARGET=cli COMMAND=build
- TARGET=cli COMMAND=test
script: ./build.sh
branches:
  only:
    - master
